### ISSUE TITLE
Running as administrator 

### ISSUE THREAD

**Issue by bruno-oliveira1** [OpenIndex/RemoteSupportTool#16]
Very nice the new version Thank you !!!
In customer version if I try to open a program as administrador Staff side see a Black screen.

**Comment by pinhead84** [comment]
Hi Bruno,

thanks for your feedback. :)

>  In customer version if I try to open a program as administrador Staff side see a Black screen.

I assume you're trying to remote control a Windows system? - As far as I know it's a known limitation (or security feature) on Windows systems, that you can't control an application at the customers machine, that was started with admin permissions.

I guess you need to the customer tool with admin permissions. In this case the staff should be able to access other admin applications. Please let me know, if this solves your problem or if I understood your question wrongly. ;)
