### ISSUE TITLE
Hi, Customer32.exe & Staff32.exe can't work

### ISSUE THREAD

**Issue by jmkim2ea** [OpenIndex/RemoteSupportTool#17]
Hi, I am Korean and My English is not good.
Recently I take this program and compile with Ubuntu by myself with downloading master.zip file.
Compile is fine, 
but when I click 32bit-exe file in the launch4j folder, it has an error [ This application requires a Java Runtime ENvironment 10(32bit)]
With [https://github.com/OpenIndex/RemoteSupportTool/releases] 's StaffSupportTool-1.0.0-win32.exe & CustomerSupportTool-1.0.0-win32.exe, it is working with my Win 10 64 bit PC.
When i search Java 10 32bit , it is not exist.
How can i solve it?
Thank have good day.

**Comment by pinhead84** [comment]
The `launch4j` folder is only used temporarily during the build process. It's not intended to run the application from this folder. Take a look at [this wiki page](https://github.com/OpenIndex/RemoteSupportTool/wiki/Development) about how to create an application bundle.

If you're working on a Windows system, it might be kind of tricky to create an application bundle. I would suggest to use a Linux system for the build process - e.g. via VirtualBox or VmWare.
