### ISSUE TITLE
Mouse is shifted on Windows clients with screen scaling > 100%

### ISSUE THREAD

**Issue by wahlbrink** [OpenIndex/RemoteSupportTool#18]
The mouse pointer of staff and customer are at a different positions.

It is only correct a the top left corner.
I guess this is caused by the highdpi screen at customer side (windows 10 with scaling > 200%). RemoteSupportTool uses a low res screenshot, but it doesn't scale the mouse position of staff from low res to high res. To fix use native res screenhot or scale the mouse position.

**Comment by pinhead84** [comment]
Thank you for that hint. I wasn't aware of this. 

I'll try to reproduce this issue - but currently I don't have a Windows 10 system with a high resolution screen. Does this problem also occur on an old school screen with scaling > 100%?

**Comment by pinhead84** [comment]
Now I had some time to verify this issue. I don't have a high resolution screen to test this issue on Windows. But the same problem occurs, if the text size in the control panel is increased to more than 100%. I guess it's the same cause of the problem for high resolution monitors.

Now that I'm able to reproduce this issue, a bugfix is in sight. ;)
