### ISSUE TITLE
Urls in openjdk init* scripts wrong

### ISSUE THREAD

**Issue by horli** [OpenIndex/RemoteSupportTool#19]
The urls to AdoptOpenJDK in the openjdk init scripts did not work. Please find the working ones in the diff.
A nice enhancement would be if the init scripts would check the exit value of curl for easy and obvious detection of changing urls in the future.

diff --git a/release/share/openjdk/init-linux64.sh b/release/share/openjdk/init-linux64.sh
index ea7ca59..c06bbdb 100755
--- a/release/share/openjdk/init-linux64.sh
+++ b/release/share/openjdk/init-linux64.sh
@@ -25,7 +25,8 @@
 # -----------------------------------------------------------------------
 
 TARGET="linux64"
-TARGET_JDK="https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2.13.tar.gz"
+TARGET_JDK="https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2+13.tar.gz"
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 DOWNLOADS_DIR="$DIR/downloads"
diff --git a/release/share/openjdk/init-windows64.sh b/release/share/openjdk/init-windows64.sh
index 95bc9fb..89dd620 100755
--- a/release/share/openjdk/init-windows64.sh
+++ b/release/share/openjdk/init-windows64.sh
@@ -25,7 +25,8 @@
 # -----------------------------------------------------------------------
 
 TARGET="windows64"
-TARGET_JDK="https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Windows_jdk-10.0.2.13.zip"
+TARGET_JDK="https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Win_jdk-10.0.2+13.zip"

 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 DOWNLOADS_DIR="$DIR/downloads"
diff --git a/release/share/openjdk/init.sh b/release/share/openjdk/init.sh
index f3a8c75..c1a47e1 100755
--- a/release/share/openjdk/init.sh
+++ b/release/share/openjdk/init.sh
@@ -39,7 +39,7 @@ case "$SYSTEM" in
     case "$SYSTEM_ARCH" in
         x86_64)
           echo "Initializing Linux 64bit environment..."
-          SYSTEM_JDK="https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2.13.tar.gz"
+          SYSTEM_JDK="https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2+13.tar.gz"
           ;;
         i686)

**Comment by pinhead84** [comment]
Thank you for pointing this out. I've fixed the download URL's with [this commit](https://github.com/OpenIndex/RemoteSupportTool/commit/16272a31273d7f0594e8787658a9c0cae8bd7f2e) and cherry picked the changes into the [master branch](https://github.com/OpenIndex/RemoteSupportTool/tree/master).

By the way, I'm planning to migrate the application to Java 11 and rework the init scripts a little bit. The next commits in the [develop branch](https://github.com/OpenIndex/RemoteSupportTool/tree/develop) will migrate the application accordingly.
