### ISSUE TITLE
Can't compile the application

### ISSUE THREAD

**Issue by K4bl0-Skat3R** [OpenIndex/RemoteSupportTool#27]
error while compile 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.                8.0:compile (default-compile) on project RemoteSupportTool-Core: Fatal error com 
![ERRORGIT](https://user-images.githubusercontent.com/7777728/54657362-eac0ab80-4aa7-11e9-918a-bbbbccc31084.jpg)

**Comment by K4bl0-Skat3R** [comment]
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
$ javac -version
javac 1.8.0_92

**Comment by pinhead84** [comment]
You need at least Java 11 in order to compile the application. You can download it from [BellSoft](https://www.bell-sw.com/) or [AdoptOpenJDK](https://adoptopenjdk.net/).

**Comment by pinhead84** [comment]
By the way: Take a look at [this wiki page](https://github.com/OpenIndex/RemoteSupportTool/wiki/Development) for further notes about compiling the application for yourself.

**Comment by K4bl0-Skat3R** [comment]
I'll try now! thx a lot.

**Comment by K4bl0-Skat3R** [comment]
hello bro pinhead84 I was compiled successfully but the jars files not open the interface customer
![sucessBuld](https://user-images.githubusercontent.com/7777728/54698980-fa270f80-4b0e-11e9-804f-d016f6ea6565.jpg)
whats the jar file is the correct after build, in target folder of customer any jar file is found, any idea?

**Comment by pinhead84** [comment]
Compilation is only the first step. You also need to [obtain OpenJDK 11 for the different target platforms](https://github.com/OpenIndex/RemoteSupportTool/wiki/Development#obtain-openjdk-for-cross-platform-bundling). Afterwards you need to [prepare the release](https://github.com/OpenIndex/RemoteSupportTool/wiki/Development#prepare-the-release) and [create the application bundles](https://github.com/OpenIndex/RemoteSupportTool/wiki/Development#create-application-bundles) (self extracting EXE launcher, macOS application bundle, SH launcher for Linux).

According to your screenshots it looks like you're using Windows? - We currently don't have any build scripts for Windows systems, that will do these tasks automatically. If possible I would suggest to use Linux or macOS, if you like to create the application bundles for all target platforms. In this case you only need to launch some scripts. The whole stuff is documented on the [development wiki page](https://github.com/OpenIndex/RemoteSupportTool/wiki/Development).

But if you only like to do some testing, you can download the EXE files from the [release page](https://github.com/OpenIndex/RemoteSupportTool/releases). These files are basically 7zip archives, which you can open and extract with 7zip. In the extracted folder you can put your modified / compiled JAR files into the `modules` subfolder and execute the applications via `Start.exe` in the `bin` subfolder. For simple testing this approach might be helpful. 

Theoretically you can create your own EXE application bundles with 7zip after you've copied your modified JAR files into the extracted folder (as described [here](https://superuser.com/questions/283698/create-7-zip-sfx-executable)). It currently won't work automatically, but with some handwork you can also build these files on Windows systems.

**Comment by K4bl0-Skat3R** [comment]
great notes bro I have Debian here, I'll update jdk and test it on my Stretch

**Comment by K4bl0-Skat3R** [comment]
after compile mvn-install.sh ![LinuxBuild](https://user-images.githubusercontent.com/7777728/54729530-e3aaa380-4b62-11e9-81e1-ee220c58a1d7.jpg)
build done!

**Comment by K4bl0-Skat3R** [comment]
I was installed jdk 11 and mvn to work but now whats the jar file load app 
![whatsJAR](https://user-images.githubusercontent.com/7777728/54729639-70556180-4b63-11e9-9ea8-591a3efee051.jpg)
my system break down after load some jars

**Comment by pinhead84** [comment]
In the first step launch [`release/openjdk-init.sh`](https://github.com/OpenIndex/RemoteSupportTool/blob/master/release/openjdk-init.sh), which will download OpenJDK for the different platforms. You only need to run this command once.

Afterwards launch [`mvn-release.sh`](https://github.com/OpenIndex/RemoteSupportTool/blob/master/mvn-release.sh), which compiles the application **and** assembles the application folders in `release/target/Customer` and `release/target/Staff` (including previously downloaded OpenJDK).

In the last step launch the `release/bundle-*.sh` scripts, which will bundle the previously created application folders into single executable files. These are saved into `release/target`.

**Comment by K4bl0-Skat3R** [comment]
![after_mvn-release sh](https://user-images.githubusercontent.com/7777728/54730491-068b8680-4b68-11e9-89c3-3e46c9453184.jpg)
first of all I run install.sh next mvn-release.sh but in the release don't have openjdk-init.sh
![Into_ReleaseFolder](https://user-images.githubusercontent.com/7777728/54730546-536f5d00-4b68-11e9-8289-94360f32b499.jpg)

**Comment by K4bl0-Skat3R** [comment]
![fromRelease](https://user-images.githubusercontent.com/7777728/54730750-5585eb80-4b69-11e9-937c-870524d10382.jpg)
running mvn-release.sh from release folder the process build bring me this error

**Comment by pinhead84** [comment]
In my last comment I've posted / linked the files, you are supposed to launch:

> In the first step launch [`release/openjdk-init.sh`](https://github.com/OpenIndex/RemoteSupportTool/blob/master/release/openjdk-init.sh), which will download OpenJDK for the different platforms. You only need to run this command once.
> 
> Afterwards launch [`mvn-release.sh`](https://github.com/OpenIndex/RemoteSupportTool/blob/master/mvn-release.sh), which compiles the application **and** assembles the application folders in `release/target/Customer` and `release/target/Staff` (including previously downloaded OpenJDK).
> 
> In the last step launch the `release/bundle-*.sh` scripts, which will bundle the previously created application folders into single executable files. These are saved into `release/target`.

By the way, you should use version 1.1.0. We've made some changes to the build process and not all of my comments may be valid for the older 1.0.1 version.

**Comment by K4bl0-Skat3R** [comment]
I tested now on version 1.0
![secretkey](https://user-images.githubusercontent.com/7777728/54731599-e65ec600-4b6d-11e9-9a06-7fa399ca5f9c.jpg)
is really need the secret key?

**Comment by pinhead84** [comment]
No. Use version 1.1.0 or the latest development branch. Build scripts have been significantly changed.

> is really need the secret key?

In the old version you had to manually disable GPG signatures. This is not necessary anymore with the latest release / development branch.

**Comment by K4bl0-Skat3R** [comment]
I'll wait for new releases, but thank you 4all helps bro. see yo

**Comment by pinhead84** [comment]
Read the [documentation](https://github.com/OpenIndex/RemoteSupportTool/wiki/Development), follow the documentation, use the latest version and everything will be fine.

**Comment by K4bl0-Skat3R** [comment]
after update all dependencies whats the step by step... I was launched release/openjdk init.sh, than I launched mvn-release.sh and build 
![aLLOKInstalled2019-03-23_00-31-53](https://user-images.githubusercontent.com/7777728/54861203-44bdad00-4d04-11e9-9373-ccf4af4ce559.jpg)
is this correct step?
![aLLOKInstalled2019-03-23_00-31-53](https://user-images.githubusercontent.com/7777728/54861236-b269d900-4d04-11e9-9cc6-75e45c5a00c3.jpg)
I run vn-install.sh first?

**Comment by K4bl0-Skat3R** [comment]
after update all dependencies whats the step by step... I was launched release/openjdk init.sh, than I launched mvn-release.sh and build
 
![aLLOKInstalled2019-03-23_00-31-53](https://user-images.githubusercontent.com/7777728/54861266-1096bc00-4d05-11e9-8aeb-31694b57d290.jpg)

is this correct step?
![whats the file do run first2019-03-23_00-42-16](https://user-images.githubusercontent.com/7777728/54861268-24dab900-4d05-11e9-927e-d2008a2df87d.jpg)

I run mvn-install.sh first? I already try this proccess

**Comment by K4bl0-Skat3R** [comment]
![DownloadingopenJDK](https://user-images.githubusercontent.com/7777728/54861307-d4b02680-4d05-11e9-8102-3e0459883402.jpg)
I think that was missing...

**Comment by K4bl0-Skat3R** [comment]
![afterALLerrorAgain](https://user-images.githubusercontent.com/7777728/54862283-21502d80-4d17-11e9-9fe6-214c526a8826.jpg)
after hours to download all files :/

**Comment by pinhead84** [comment]
The first steps were correct. You've already started `release/openjdk-init.sh` and don't need to bother about that anymore.

Your mistake was, that you should have run `mvn-release.sh` from the root directory of the repository - not from the `release` subfolder. This will compile the application and assemble all files required to start the application into the `release/target/Customer` and `release/target/Staff` folder. 

- For example to start customer tool on Linux x86-64, you might launch `release/target/Customer/linux-x86-64/bin/Start.sh`.
- Or you can copy the folder `release/target/Customer/windows-x86-64` to Windows 64bit and start the application via `bin/Start.exe`.

To create the application bundles, that contain all the application files and can easily be sent to other users, you can finally run the `release/bundle-*.sh` scripts. The created application bundles are stored into the `release/target` folder. These application bundles are also published on our [release page](https://github.com/OpenIndex/RemoteSupportTool/releases).

---

As an alternative you can run all steps at once with this command:

```bash
export JAVE_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && \
  rm -Rf RemoteSupportTool && \
  git clone https://github.com/OpenIndex/RemoteSupportTool.git && \
  cd RemoteSupportTool && \
  ./release/openjdk-init.sh && \
  ./mvn-release.sh && \
  ./release/bundle-linux.sh && \
  ./release/bundle-macos.sh && \
  ./release/bundle-windows.sh
```

Copy the whole command at once into your console, replace the path to your OpenJDK installation and press ENTER. The whole process might take a while, because once again all required OpenJDK versions have to be downloaded. Afterwards the application bundles are finally stored into the `RemoteSupportTool/release/target` folder.

**Comment by K4bl0-Skat3R** [comment]
I back dir folder and run mvn-release.sh again
![back_Dir_and_Build](https://user-images.githubusercontent.com/7777728/54868108-a2cfac00-4d67-11e9-827e-d3194eb268b0.jpg)
Wow unbelievable!!
![AllDone_GreatNotes_pinhead84](https://user-images.githubusercontent.com/7777728/54868136-0063f880-4d68-11e9-852c-ce4136e0063a.jpg)
thanx a lot pinhead!! now lets try your tool! I was searching for something remote tools, like this. I think this tool can help me.
