### ISSUE TITLE
BIN Files

### ISSUE THREAD

**Issue by gvsurenderreddy** [OpenIndex/RemoteSupportTool#36]
Hello sir c
can you provide binaries please .Bin Files are in German can u do it in English too please

**Comment by pinhead84** [comment]
The binaries on the [release page](https://github.com/OpenIndex/RemoteSupportTool/releases) are in English & German language.

**Comment by gvsurenderreddy** [comment]
Thank you so much Sir Staff support only Works on Localhost What if i want to add IP ?

**Comment by gvsurenderreddy** [comment]
Thank you so much for the wonderful software it help me a lot Thankyou
