### ISSUE TITLE
Support tool is 1-1 or 1-N

### ISSUE THREAD

**Issue by gvsurenderreddy** [OpenIndex/RemoteSupportTool#37]
Hello sir 

Can you tell me is this Software works for more than 1 client and support staff or 1 to many or many to 1 .Can you tell me please

**Comment by pinhead84** [comment]
During a support session the staff can only connect to one customer / client. But of course the staff might connect to a different customer somewhere else in the world after the support session was finished.

If the staff likes to connect to different customers at the same time, he might start a second instance of the staff application and select another port number. We don't really need this scenario in our daily use - but generally it should be possible.
