### ISSUE TITLE
bundle-windows.sh: line 92: : command not found

### ISSUE THREAD

**Issue by slashinpdx** [OpenIndex/RemoteSupportTool#38]

**Comment by pinhead84** [comment]
The file is definitely present in the repository at [`release/bundle-windows.sh`](https://github.com/OpenIndex/RemoteSupportTool/blob/master/release/bundle-windows.sh).

Can you please check, if you already have this file on your local repository and that the file is executable?

**Comment by pinhead84** [comment]
I guess I was wrong with my last assumption. Please install 7zip on your linux system. The binary `7z` should be available in your path environment in order to build the Windows package (which is a self extracting 7zip archive).

**Comment by slashinpdx** [comment]
Mr. Rudolph:

Hi there.  Thanks for the suggestion and response.

I'd followed the instructions perfectly (a couple of times) and the only bundle command that failed was this one.  The others worked fine.  I thought it might have been because I'd installed Ubuntu (18.04) with the minimal option in a Windows 10 Hyper-V virtual machine so I reinstalled the O/S as a full install and still had the same error message.

I've since decided to go back to uvnc single-click as I found an option to bypass the connection screen for clients which I'd been previously unaware of.   Granny is a bit older and has trouble double-clicking on the text in the white box (what an odd design) to get me connected.

Again, thanks.  Sorry to have wasted your time.

Steve

**Comment by pinhead84** [comment]
No problem.

I guess I found the solution to the problem. Ubuntu's `p7zip` package does not contain the `7z` application (see [package contents](https://packages.ubuntu.com/bionic/amd64/p7zip/filelist)). Instead you should have installed the `p7zip-full` package (see [package contents](https://packages.ubuntu.com/bionic/amd64/p7zip-full/filelist)).

The same applies to Debian. Therefore our documentation is wrong and needs an update. Or maybe we also can change the `bundle-windows.sh` script. I'll investigate this in the next days.

**Comment by slashinpdx** [comment]
Good to know.  I'll get better try later today and get back to you. Thanks!
________________________________

**Comment by slashinpdx** [comment]
From a fresh install of Ubuntu 18.04 and after installing git then updating everything:

Following instructions from: https://github.com/OpenIndex/RemoteSupportTool/wiki/Development

1.  cd ~/Desktop
2.  git clone https://github.com/OpenIndex/RemoteSupportTool
3.  sudo apt install makeself p7zip-full gnupg maven wine curl
4.  cd RemoteSupportTool/release
5.  ./openjdk-init.sh
5.  cd ..
6.  ./mvn-install.sh
7.  ./mvn-release.sh
8.  cd release
9.  ./bundle-windows.sh !! success !!
10.  ./bundle-macos.sh
11.  ./bundle-linux.sh

Thank you!
