### ISSUE TITLE
Windows 10: OpenSSH Server not starting 

### ISSUE THREAD

**Issue by nwtti** [OpenIndex/RemoteSupportTool#6]
OpenSSH doesn't start when I try to connect from a Windows 10 Machine via the GUI, but it is working if I start it from CMD without the -f parameter (and without sleep 15). Does somebody know what to do, to make it working? From Linux its just working fine.

**Comment by pinhead84** [comment]
On Windows systems we're using a bundled version of OpenSSH. Maybe this bundle isn't extracted properly or does not work properly under Windows 10. You can try to install [OpenSSH for Windows](https://www.mls-software.com/opensshd.html) separately and set the path to `ssh.exe` in the extended settings. It would be interesting / helpful to know, if the problem also occurs in this case.

Btw: Does the GUI application create a log file, when you try to establish a connection? - If yes, does it contain some informations / error messages?

**Comment by pinhead84** [comment]
This issue should be resolved with the reworked [version 1.0.0](https://github.com/OpenIndex/RemoteSupportTool/releases/tag/v1.0.0) because an integrated OpenSSH for Windows is not required anymore.
