### ISSUE TITLE
More customization 

### ISSUE THREAD

**Issue by bruno-oliveira1** [OpenIndex/RemoteSupportTool#7]
First of all thank for your awesome project, my issue is how add more host and port fields and the possibility to substitute iP by a number or name.

**Comment by pinhead84** [comment]
Sorry for my late response. What exactly are your trying to achieve?

In general I would suggest to use SSH tunneling (remote port forwarding) on the supporter side. In this case the customer can always use the same hostname / IP address (the hostname of the SSH server) and possibly only needs to change the SSH port number.

We're going to release a new version of RemoteSupportTool soon, which will make this scenario a lot easier for the customer and support staff.

**Comment by pinhead84** [comment]
We've released the reworked [version 1.0.0](https://github.com/OpenIndex/RemoteSupportTool/releases/tag/v1.0.0). Using SSH tunneling is a lot easier now. Therefore I suggest, that you're trying this feature with the new version. Possibly no further customizations are necessary?
