### ISSUE TITLE
Window opens off the screen.

### ISSUE THREAD

**Issue by ajhalls** [OpenIndex/RemoteSupportTool#8]
I am not sure how to debug this. I have some experience with C#, but none with TCL. The window location is off the screen on my multi monitor setup when I launch the application. I am not sure where to even begin making those modifications since for the most part the TCL seems to be a bundling script as opposed to a full programing language

**Comment by pinhead84** [comment]
For your information: We're going to release a completely rewritten version of this application in the Java language soon. I'm quite sure, that your multi monitor issue won't occur afterwards. On my multi monitor setup our new version does not make any problems. And even if the problem still occurs on your side - a fix should be a lot easier to find. ;)

**Comment by pinhead84** [comment]
This issue should be resolved with the reworked [version 1.0.0](https://github.com/OpenIndex/RemoteSupportTool/releases/tag/v1.0.0). Please let me know, if you can confirm this.
